baseURL = "/"
title = "$10 Site"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "A $10 Site" # title for frontpage, may include image
copyright = "John Doe"
description = 'Is not difficult<br />to build<br />as long as you are willing to try.<br />'
startbuttonText = "See?"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Themes let you change everything. Like this headline.'
body = '''
This section could be about anything. 
Maybe it's about how you help customers create the stories that sell their products. 
Or maybe it's about lemon curd. Who knows!? 
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
class = ""
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'The point is<br />everything is customizable'
body = 'You simply need to be willing to get comfortable being uncomfortable. Or maybe you are super technical already? In which case this will be a snap.'

[[params.two.section]]
class = ""
img = "img/pic02.jpg"
title = 'Change this...<br />to this.'
body = "And if you want, you can leave a bunch of lorem ipsum here. It's your site, do what you augue consectetur interdum."

[[params.two.section]]
class = "pink"
img = "img/pic03.jpg"
title = 'You can even<br />change colors'
body = 'But one of the nice things about themes is that someone with a solid design sense has usually gotten there ahead of you. Maybe pink was a bad idea here...'

[params.three]
enable = true
title = "And that's about it"
body = '''
Dive into the code. Make mistakes. Learn. And before you know it,
you will have a website you can be proud of, for less than a couple of
large coffees.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Change"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "These"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "If"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "You"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Want"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Or not."
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Here's your call to action"
body = "You are the best! Yell it to the highest mountain!"

[[params.cta.link]]
href = "#"
text = "Call Me"
special = true

[[params.cta.link]]
href = "#"
text = "Maybe"
special = false

[params.contact]
enable = true
title = "This theme, like most of them, also comes with a contact form."
body = "And that's it."
phone = "(000) 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
